Updating @clerk/clerk-expo to version 0.17.6
clerkinc/t3-turbo-and-clerk pull request #82
Opened 2023-05-31 19:27 UTC by DontAskForAnything

2023-05-31 20:32 UTC, dominikwozniak approved these changes

2023-05-31 20:37 UTC, perkinsjr requested changes

2023-05-31 20:44 UTC, DontAskForAnything commented on apps/expo/src/components/SignInWithOAuth.tsx
> +      if (createdSessionId && setActive) {
Without this check `tsc` throw TS2722, because `const setActive: SetActive | undefined`
```ts
src/components/SignInWithOAuth.tsx:16:9 - error TS2722: Cannot invoke an object which is possibly 'undefined'.
```

2023-06-06 20:51 UTC, perkinsjr approved these changes

2023-06-06 20:53 UTC, merged